version: '3.8'

services:
  web:
    build: .
    container_name: rss_scraper
    ports:
      - "5000:5000"
    networks:
      - scraper_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80"  # Host port 8080 mapped to Nginx port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - scraper_network

networks:
  scraper_network:
    driver: bridge
